version: "3.7"

services:
  front-end:
    depends_on:
      - back-end
    build: allrise/.
    image: allrise
    ports: 
      - 8080:80

  db:
    container_name: db
    image: mysql:5.7
    volumes:
        # imports database into the mysql server
      - ./backend/database/all_rise.sql:/docker-entrypoint-initdb.d/all_rise.sql
 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: all_rise
    # network_mode: host
    ports:
      - "3306:3306"
    networks:
      - backend

  back-end:
    depends_on:
      - db
    build: backend/.
    image: allrise-backend
    environment: 
      DB_HOST : db
      DB_PORT : 3306
      DB_NAME : all_rise  
    ports: 
      - 3000:3000
    networks:
      - backend
    entrypoint: ["/wait-for-it.sh", "db:3306", "-t", "120", "--","npm", "run", "start"]
networks:
  backend: